#!/bin/bash

if [ "$1" == "clean" ]
	then
		echo "Cleaning..."
		rm obj/* -rvf
		rm src/*~ -fv
		rm exe/main -fv
		for f in `find latex/ -not -name "*.tex"`;
		do
			if [ -f "$f" ]
			then
				rm "$f" -fv
			fi;
		done;
		echo "Done"
		exit 1
fi;

pdflatex latex/report.tex > /dev/null
echo "Report compiled"
make
echo " --------- STARTED -----------"
cd exe/
./main $@
cd ..
echo " --------- DONE -----------"

