#!/bin/bash

if [ "$1"=="clean" ]
	then
		echo "Cleaning..."
		rm obj/* -rf
		rm src/*~ -f
		rm exe/main -f
		cd latex/
		for f in `find . -not -name "*.tex"`;
		do
			if [ -f "$f" ]
			then
				rm "$f";
			fi;
		done;
		cd ..
		echo "Done"
		exit 1
fi;

make
echo " --------- STARTED -----------"
cd exe/
valgrind ./main $@
cd ..
echo " --------- DONE -----------"
make clean
